<Project>

  <PropertyGroup>
    <Version>1.0.1</Version>
    <Product>Starlog</Product>
    <Authors>Dima Kravtsov</Authors>
    <Description>Simple log files reader</Description>
    <RepositoryUrl>https://github.com/hwndmaster/starlog</RepositoryUrl>

    <RootNamespace>Genius.$(MSBuildProjectName)</RootNamespace>
    <AssemblyName>$(RootNamespace)</AssemblyName>

    <AtomPackageVersion>0.0.43</AtomPackageVersion>
    <AtomBuildDirectory>$(USERPROFILE)\.nuget\packages\genius.atom.build\$(AtomPackageVersion)\build</AtomBuildDirectory>
  </PropertyGroup>

  <Import Project="$(AtomBuildDirectory)\Genius.Atom.Build.props" />
  <Import Project="$(AtomBuildDirectory)\AtomReferences.targets" />

  <!-- Automated Testing components -->
  <ItemGroup Condition="$(IsTestProject) Or $(MSBuildProjectName.EndsWith('.TestingUtil'))">
    <Using Include="AutoFixture.AutoFakeItEasy" />
  </ItemGroup>
</Project>
