using System.Windows.Controls;
using System.Windows.Data;
using Genius.Starlog.UI.ValueConverters;
using Genius.Starlog.UI.Views;
using Microsoft.Xaml.Behaviors;

namespace Genius.Starlog.UI.Behaviors;

public sealed class LogColorizeBehavior : Behavior<DataGrid>
{
    protected override void OnAttached()
    {
        AssociatedObject.AutoGeneratedColumns += OnAutoGeneratedColumns;

        base.OnAttached();
    }

    protected override void OnDetaching()
    {
        AssociatedObject.AutoGeneratedColumns -= OnAutoGeneratedColumns;

        base.OnDetaching();
    }

    private void OnAutoGeneratedColumns(object? sender, EventArgs args)
    {
        var bindingForLogLevel = new Binding(".")
        {
            Converter = new LogLevelToColorConverter(AssociatedObject)
        };
        var trigger1 = CreateDummyTrigger(false, bindingForLogLevel);

        var bindingForLogThread = new Binding(".")
        {
            Converter = new LogFieldToColorConverter()
        };
        var trigger2 = CreateDummyTrigger(true, bindingForLogThread);

        foreach (var column in AssociatedObject.Columns)
        {
            var cellStyle = new Style(column.CellStyle.TargetType, column.CellStyle);
            cellStyle.Triggers.Add(trigger1);
            cellStyle.Triggers.Add(trigger2);
            column.CellStyle = cellStyle;
        }

        static DataTrigger CreateDummyTrigger(bool forValue, Binding binding)
        {
            var trigger = new DataTrigger()
            {
                Binding = new Binding(nameof(ILogItemViewModel.ColorizeByField)),
                Value = forValue
            };
            trigger.Setters.Add(new Setter(Control.ForegroundProperty, binding));
            return trigger;
        }
    }
}
