name: Starlog CD

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Add Nuget source
      run: dotnet nuget add source https://nuget.pkg.github.com/hwndmaster/index.json -n github -u hwndmaster -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
    - name: Build
      run: dotnet build "./Starlog.UI/Starlog.UI.csproj" -r "win-x64" -c Release --self-contained false
    - name: Create release (clean)
      shell: bash
      run: |
        tag=$(git describe --tags --abbrev=0)
        release_name="Starlog-$tag-x64"
        echo "release_name=${release_name}" >> $GITHUB_ENV
        dotnet publish -r win-x64 -c Release -o "${release_name}" --self-contained false //p:DebugType=None //p:DebugSymbols=false "./Starlog.UI/Starlog.UI.csproj"
        7z a -tzip "${release_name}.zip" "./${release_name}/*"
        rm -r "$release_name"
    # - name: Create release (self contained)
    #   shell: bash
    #   run: |
    #     tag=$(git describe --tags --abbrev=0)
    #     release_name_sc="Starlog-$tag-bundle-x64"
    #     dotnet publish --runtime win-x64 -c Release -o "${release_name_sc}" --self-contained true --no-restore --no-build /p:DebugType=None /p:DebugSymbols=false ./Starlog.UI/Starlog.UI.csproj
    #     7z a -tzip "${release_name_sc}.zip" "./${release_name_sc}/*"
    #     rm -r "$release_name_sc"
    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{env.release_name}}.zip
    #      ${release_name_sc}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
